name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: embed_example/app
    runs-on: macos-latest
    continue-on-error: ${{matrix.experimental || false }}
    strategy:
      matrix:
        rust: [nightly, stable]

        include:
          - rust: stable
            experimental: true
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install all Rust targets
        run: rustup target install thumbv7m-none-eabi
      - name: Build
        run: cargo build --verbose
